name: CI/CD Pipeline for Portfolio

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. SonarQube Analysis Job
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=amankrs21_Portfolio
            -Dsonar.organization=amankrs21
          projectBaseDir: .


  # 2. Express App Hosting Job (depends on SonarCloud success, but only runs on push to `main`)
  cloudflare:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: sonarqube
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for React app
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'amankrs21'
          directory: 'dist'
